@startuml

component core {
    package bankapp.core
    package bankapp.Files
}

bankapp.core ..> bankapp.Files
component jackson {
}


component fxui {
    package java.ui
}

java.ui ..> bankapp.core
java.ui ..> bankapp.Files
bankapp.Files ..> jackson

component javafx {
    component fxml
}

fxui ..> javafx
fxui ..> fxml


@enduml